"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 11:22:46.430139
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("last_scan_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("competitor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_competitor_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_competitor_page_id"), ["page_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_competitor_slug"), ["slug"], unique=True)

    op.create_table(
        "scan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competitor_id", sa.Integer(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("search_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("platforms", sa.JSON(), nullable=True),
        sa.Column("active_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_ads", sa.Integer(), nullable=False),
        sa.Column("exact_page", sa.Boolean(), nullable=False),
        sa.Column("headless", sa.Boolean(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_results", sa.Integer(), nullable=True),
        sa.Column("ads_found", sa.Integer(), nullable=False),
        sa.Column("ads_processed", sa.Integer(), nullable=False),
        sa.Column("ads_failed", sa.Integer(), nullable=False),
        sa.Column("new_ads", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("block_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("log_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_competitor_id"), ["competitor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_status"), ["status"], unique=False)

    op.create_table(
        "ad",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("competitor_id", sa.Integer(), nullable=False),
        sa.Column("page_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_profile_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("days_running", sa.Integer(), nullable=False),
        sa.Column("platforms", sa.JSON(), nullable=True),
        sa.Column("ad_copy", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("headline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cta_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cta_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("landing_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("display_format", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_urls", sa.JSON(), nullable=True),
        sa.Column("thumbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("variation_count", sa.Integer(), nullable=False),
        sa.Column("collation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumbnail_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("media_paths", sa.JSON(), nullable=True),
        sa.Column("raw_html", sa.LargeBinary(), nullable=True),
        sa.Column("raw_json", sa.LargeBinary(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=True),
        sa.Column("first_seen_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("last_scan_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_scan_id"],
            ["scan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ad", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ad_competitor_id"), ["competitor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ad_library_id"), ["library_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_ad_page_id"), ["page_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ad_score"), ["score"], unique=False)

    op.create_table(
        "adsnapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("variation_count", sa.Integer(), nullable=False),
        sa.Column("days_running", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("captured_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ad_id", "scan_id"),
    )
    with op.batch_alter_table("adsnapshot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_adsnapshot_ad_id"), ["ad_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_adsnapshot_scan_id"), ["scan_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adsnapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adsnapshot_scan_id"))
        batch_op.drop_index(batch_op.f("ix_adsnapshot_ad_id"))

    op.drop_table("adsnapshot")
    with op.batch_alter_table("ad", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_score"))
        batch_op.drop_index(batch_op.f("ix_ad_page_id"))
        batch_op.drop_index(batch_op.f("ix_ad_library_id"))
        batch_op.drop_index(batch_op.f("ix_ad_competitor_id"))

    op.drop_table("ad")
    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_status"))
        batch_op.drop_index(batch_op.f("ix_scan_created_at"))
        batch_op.drop_index(batch_op.f("ix_scan_competitor_id"))

    op.drop_table("scan")
    with op.batch_alter_table("competitor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competitor_slug"))
        batch_op.drop_index(batch_op.f("ix_competitor_page_id"))
        batch_op.drop_index(batch_op.f("ix_competitor_name"))

    op.drop_table("competitor")
    # ### end Alembic commands ###
