"""reports table

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 11:40:47.148042
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.Column("competitor_ids", sa.JSON(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("html_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pdf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_created_at"), ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_created_at"))

    op.drop_table("report")
    # ### end Alembic commands ###
