"""grouping landing pages ai analysis

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 12:13:36.912174
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("done", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("cached", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("estimate_usd", sa.Float(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "landingpage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("final_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("captured_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("landingpage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_landingpage_url_key"), ["url_key"], unique=True)

    op.create_table(
        "adanalysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hook_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hook_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("emotion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("offer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cta", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_audience_guess", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("one_line_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("what_to_steal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["airun.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adanalysis", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_adanalysis_ad_id"), ["ad_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_adanalysis_library_id"), ["library_id"], unique=True)

    with op.batch_alter_table("ad", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phash", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("copy_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("group_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("group_size", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column("group_creatives", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column("group_copies", sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_index(batch_op.f("ix_ad_group_key"), ["group_key"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ad", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_group_key"))
        batch_op.drop_column("group_copies")
        batch_op.drop_column("group_creatives")
        batch_op.drop_column("group_size")
        batch_op.drop_column("group_key")
        batch_op.drop_column("copy_hash")
        batch_op.drop_column("phash")

    with op.batch_alter_table("adanalysis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adanalysis_library_id"))
        batch_op.drop_index(batch_op.f("ix_adanalysis_ad_id"))

    op.drop_table("adanalysis")
    with op.batch_alter_table("landingpage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_landingpage_url_key"))

    op.drop_table("landingpage")
    op.drop_table("airun")
    # ### end Alembic commands ###
