"""watchlist and change events

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 12:28:57.163323
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlistitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competitor_id", sa.Integer(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("search_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_ads", sa.Integer(), nullable=False),
        sa.Column("exact_page", sa.Boolean(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("last_scan_id", sa.Integer(), nullable=True),
        sa.Column("next_run_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_scan_id"],
            ["scan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlistitem_competitor_id"), ["competitor_id"], unique=True)

    op.create_table(
        "changeevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competitor_id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("changeevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_changeevent_ad_id"), ["ad_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_changeevent_competitor_id"), ["competitor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_changeevent_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_changeevent_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_changeevent_scan_id"), ["scan_id"], unique=False)

    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("trigger", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="manual")
        )
        batch_op.add_column(sa.Column("change_summary", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan", schema=None) as batch_op:
        batch_op.drop_column("change_summary")
        batch_op.drop_column("trigger")

    with op.batch_alter_table("changeevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_changeevent_scan_id"))
        batch_op.drop_index(batch_op.f("ix_changeevent_kind"))
        batch_op.drop_index(batch_op.f("ix_changeevent_created_at"))
        batch_op.drop_index(batch_op.f("ix_changeevent_competitor_id"))
        batch_op.drop_index(batch_op.f("ix_changeevent_ad_id"))

    op.drop_table("changeevent")
    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlistitem_competitor_id"))

    op.drop_table("watchlistitem")
    # ### end Alembic commands ###
