"""clients and swipe file boards

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 13:05:45.264045
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_client_name"), ["name"], unique=True)

    op.create_table(
        "board",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("board", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_board_client_id"), ["client_id"], unique=False)

    op.create_table(
        "boarditem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("added_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["board.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("board_id", "ad_id"),
    )
    with op.batch_alter_table("boarditem", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_boarditem_ad_id"), ["ad_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_boarditem_board_id"), ["board_id"], unique=False)

    with op.batch_alter_table("competitor", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_competitor_client_id"), ["client_id"], unique=False)
        batch_op.create_foreign_key("fk_competitor_client_id", "client", ["client_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("competitor", schema=None) as batch_op:
        batch_op.drop_constraint("fk_competitor_client_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_competitor_client_id"))
        batch_op.drop_column("client_id")

    with op.batch_alter_table("boarditem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_boarditem_board_id"))
        batch_op.drop_index(batch_op.f("ix_boarditem_ad_id"))

    op.drop_table("boarditem")
    with op.batch_alter_table("board", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_board_client_id"))

    op.drop_table("board")
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_name"))

    op.drop_table("client")
    # ### end Alembic commands ###
